version: '3.8'

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: timescaledb
    env_file:
      - .env
    ports:
      - "55432:5432"
    volumes:
      - timescale_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    env_file:
      - .env
    ports:
      - "55050:80"
    depends_on:
      - timescaledb

volumes:
  timescale_data: 